// Generated by gencpp from file low_level/theta_dot_lr.msg
// DO NOT EDIT!


#ifndef LOW_LEVEL_MESSAGE_THETA_DOT_LR_H
#define LOW_LEVEL_MESSAGE_THETA_DOT_LR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace low_level
{
template <class ContainerAllocator>
struct theta_dot_lr_
{
  typedef theta_dot_lr_<ContainerAllocator> Type;

  theta_dot_lr_()
    : theta_dot_left(0.0)
    , theta_dot_right(0.0)  {
    }
  theta_dot_lr_(const ContainerAllocator& _alloc)
    : theta_dot_left(0.0)
    , theta_dot_right(0.0)  {
  (void)_alloc;
    }



   typedef float _theta_dot_left_type;
  _theta_dot_left_type theta_dot_left;

   typedef float _theta_dot_right_type;
  _theta_dot_right_type theta_dot_right;





  typedef boost::shared_ptr< ::low_level::theta_dot_lr_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::low_level::theta_dot_lr_<ContainerAllocator> const> ConstPtr;

}; // struct theta_dot_lr_

typedef ::low_level::theta_dot_lr_<std::allocator<void> > theta_dot_lr;

typedef boost::shared_ptr< ::low_level::theta_dot_lr > theta_dot_lrPtr;
typedef boost::shared_ptr< ::low_level::theta_dot_lr const> theta_dot_lrConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::low_level::theta_dot_lr_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::low_level::theta_dot_lr_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace low_level

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'low_level': ['/home/dlinn/acr/catkin_ws/src/low_level/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::low_level::theta_dot_lr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::low_level::theta_dot_lr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::low_level::theta_dot_lr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::low_level::theta_dot_lr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::low_level::theta_dot_lr_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::low_level::theta_dot_lr_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::low_level::theta_dot_lr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd5df01c85a05c89a29d456cc9a16601";
  }

  static const char* value(const ::low_level::theta_dot_lr_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd5df01c85a05c89ULL;
  static const uint64_t static_value2 = 0xa29d456cc9a16601ULL;
};

template<class ContainerAllocator>
struct DataType< ::low_level::theta_dot_lr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "low_level/theta_dot_lr";
  }

  static const char* value(const ::low_level::theta_dot_lr_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::low_level::theta_dot_lr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 theta_dot_left\n"
"float32 theta_dot_right\n"
"\n"
;
  }

  static const char* value(const ::low_level::theta_dot_lr_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::low_level::theta_dot_lr_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.theta_dot_left);
      stream.next(m.theta_dot_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct theta_dot_lr_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::low_level::theta_dot_lr_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::low_level::theta_dot_lr_<ContainerAllocator>& v)
  {
    s << indent << "theta_dot_left: ";
    Printer<float>::stream(s, indent + "  ", v.theta_dot_left);
    s << indent << "theta_dot_right: ";
    Printer<float>::stream(s, indent + "  ", v.theta_dot_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOW_LEVEL_MESSAGE_THETA_DOT_LR_H
